# Install node with alpine linux container
FROM node:alpine

# set app as working DIR
WORKDIR '/app'

# copy package.json to /app (container current DIR)
COPY package.json .

# run npm install command to install all dependencies
RUN npm install

# copy all containt with node_modules form current DIR to /app (container current DIR)
COPY . .

# command run our project in test mode
CMD ["npm", "run" , "start"]

